; PlatformIO Configuration for ESP32-ShiftLog
; Target: Waveshare ESP32-S2-LCD-0.96 (ST7735S 160x80 px)

[env:esp32-s2]
platform  = espressif32
board     = esp32-s2-saola-1
framework = arduino

; Upload & serial monitor
monitor_speed = 115200
upload_speed  = 921600

; Build flags
; Enable USB CDC as Serial on boot for ESP32-S2.
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

; Library dependencies
lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
    adafruit/Adafruit GFX Library @ ^1.11.11
